/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform statistics */
        get: operations["getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List featured markets */
        get: operations["getFeaturedMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated content feed */
        get: operations["getContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/{market_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a market and invalidate caches (admin) */
        post: operations["resolveMarket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blockchain/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blockchain node and contract health
         * @description Returns the health of the blockchain node and contract.
         *
         *     **`status` values:**
         *     - `healthy` – node reachable and contract readable. HTTP 200.
         *     - `degraded` – node reachable but contract read failed. HTTP 503.
         *     - `unhealthy` – node unreachable. HTTP 503.
         *
         *     `is_healthy` is `true` only when `status == "healthy"` (backwards-compatible field).
         */
        get: operations["getBlockchainHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blockchain/markets/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** On-chain market data */
        get: operations["getBlockchainMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blockchain/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform on-chain statistics */
        get: operations["getBlockchainStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blockchain/users/{user}/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bets placed by a user */
        get: operations["getUserBets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blockchain/oracle/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oracle result for a market */
        get: operations["getOracleResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blockchain/tx/{tx_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transaction status by hash */
        get: operations["getTransactionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe to newsletter */
        post: operations["newsletterSubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confirm newsletter subscription via token */
        get: operations["newsletterConfirm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unsubscribe from newsletter */
        delete: operations["newsletterUnsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/gdpr/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GDPR data export for a subscriber */
        get: operations["newsletterGdprExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/gdpr/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** GDPR data deletion for a subscriber */
        delete: operations["newsletterGdprDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/preview/{template_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview a rendered email template (admin) */
        get: operations["emailPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test email (admin) */
        post: operations["emailSendTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email analytics (admin) */
        get: operations["getEmailAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/queue/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email queue statistics (admin) */
        get: operations["getEmailQueueStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/sendgrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SendGrid event webhook receiver */
        post: operations["sendgridWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnyObject: {
            [key: string]: unknown;
        };
        BlockchainHealth: {
            network: string;
            rpc_url: string;
            latest_ledger: number;
            /**
             * @description healthy = node + contract OK; degraded = node OK but contract unreadable; unhealthy = node unreachable
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** @description true only when status is healthy (backwards-compatible) */
            is_healthy: boolean;
            contract_reachable: boolean;
            checked_at_unix: number;
            /** @enum {string} */
            data_source: "live" | "stale_cache" | "rpc_fallback";
        };
        ApiError: {
            /**
             * @description Machine-readable error code
             * @example INTERNAL_ERROR
             */
            code: string;
            /** @description Human-readable error description */
            message: string;
        };
        FeaturedMarketView: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: double */
            volume: number;
            /** Format: date-time */
            ends_at: string;
            onchain_volume: string;
            /** Format: int32 */
            resolved_outcome?: number | null;
        };
        InvalidationResult: {
            invalidated_keys: number;
        };
        NewsletterSubscribeRequest: {
            /** Format: email */
            email: string;
            source?: string;
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        NewsletterResponse: {
            success: boolean;
            message: string;
        };
        NewsletterExportResponse: {
            success: boolean;
            data: components["schemas"]["AnyObject"];
        };
        EmailTestRequest: {
            /** Format: email */
            recipient: string;
            template_name: string;
        };
        EmailTestResponse: {
            success: boolean;
            message: string;
            message_id: string;
        };
    };
    responses: {
        /** @description Internal server error */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Newsletter operation result */
        NewsletterResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["NewsletterResponse"];
            };
        };
    };
    parameters: {
        marketId: number;
        page: number;
        pageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getFeaturedMarkets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of featured markets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedMarketView"][];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getContent: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    resolveMarket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: components["parameters"]["marketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache invalidation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidationResult"];
                };
            };
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getBlockchainHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node and contract are healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockchainHealth"];
                };
            };
            500: components["responses"]["ApiError"];
            /** @description Degraded (node up, contract unreachable) or unhealthy (node down) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockchainHealth"];
                };
            };
        };
    };
    getBlockchainMarket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: components["parameters"]["marketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market chain data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getBlockchainStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getUserBets: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
            };
            header?: never;
            path: {
                /** @description Stellar address of the user */
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User bets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getOracleResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: components["parameters"]["marketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oracle result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getTransactionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    newsletterSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsletterSubscribeRequest"];
            };
        };
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
            409: components["responses"]["NewsletterResponse"];
            429: components["responses"]["NewsletterResponse"];
        };
    };
    newsletterConfirm: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
            404: components["responses"]["NewsletterResponse"];
        };
    };
    newsletterUnsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
        };
    };
    newsletterGdprExport: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriber data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsletterExportResponse"];
                };
            };
            400: components["responses"]["NewsletterResponse"];
            404: components["responses"]["NewsletterResponse"];
        };
    };
    newsletterGdprDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
        };
    };
    emailPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_name: "newsletter_confirmation" | "waitlist_confirmation" | "contact_form_auto_response" | "welcome_email";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rendered email preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    emailSendTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailTestRequest"];
            };
        };
        responses: {
            /** @description Test email result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailTestResponse"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getEmailAnalytics: {
        parameters: {
            query?: {
                template_name?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analytics data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getEmailQueueStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    sendgridWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnyObject"][];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
